server:
  port: 8090
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
app:
  jwt:
    secret: bankingSecretKey1234567890abcdefghijklmnopqrstuvwxyz
    expiration-ms: 86400000
